### ISSUE TITLE
https://baylorrae.com/contact isn't working

### ISSUE THREAD

**Issue by ghost** [BaylorRae/baylorrae.github.io#2]
No contact form appears and throws error: 
Mixed Content: The page at 'https://baylorrae.com/contact' was loaded over HTTPS, but requested an insecure resource 'http://baylorrae.wufoo.com/embed/z7x4a9/def/embedKey=z7x4a9992300&entsource=&referrer=https%3Awuslashwuslashbaylorrae.comwuslash'. This request has been blocked; the content must be served over HTTPS.

Btw I liked your Firebase Tutorial With React Hooks.

**Comment by BaylorRae** [comment]
Thanks for looking into this, hopefully it’ll be an easy fix!

Firebase and React are a great combo and I’m glad you liked the tutorial.

Thank you!!
